version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: dim_date
        description: Date dimension created in Fabric Warehouse.

      - name: dim_symbol
        description: Symbol dimension created from Finnhub profile2.

      - name: fact_basic_financials
        description: Finnhub company basic financials extracted via /stock/metric.